[application]
# App (Project) Name
name = "provoit-front"
# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"
# `build` & `serve` dist path
out_dir = "dist"
# resource (public) file folder
asset_dir = "public"


[web.app]
# HTML title tag content
title = "Provoit"


[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = false
# which files or dirs will be watcher monitoring
watch_path = ["src"]


# include `assets` in web platform
[web.resource]
# CSS style file
style = ["pico.min.css"]
# Javascript code file
script = []


[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
