name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Code lint, format & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev

      # Cache .cargo to avoid installing dioxus-cli
      - name: Dioxus cli cache
        id: cache-dioxus-cli
        uses: actions/cache@v3
        env:
          cache-name: cache-dioxus-cli
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo

      # Install dioxus cli if cache misses
      - name: Dioxus cli install
        if: ${{ steps.cache-dioxus-cli.outputs.cache-hit != 'true' }}
        run: cargo install dioxus-cli

      - name: Format
        run: |
          cargo fmt --verbose --check
          dioxus fmt --check

      - name: Lint
        run: cargo clippy --verbose --no-deps

      - name: Test
        run: cargo test --verbose --locked

      - name: Docs
        run: cargo doc --verbose --no-deps --locked

  build:
    name: Wasm build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rustup wasm target
        run: rustup target add wasm32-unknown-unknown

      # Cache .cargo to avoid installing dioxus-cli
      - name: Dioxus cli cache
        id: cache-dioxus-cli
        uses: actions/cache@v3
        env:
          cache-name: cache-dioxus-cli
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo

      # Install dioxus cli if cache misses
      - name: Dioxus cli install
        if: ${{ steps.cache-dioxus-cli.outputs.cache-hit != 'true' }}
        run: cargo install dioxus-cli

      - name: Build
        run: dioxus build --platform web

  build-desktop:
    name: Build for ${{ matrix.os }} desktop
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # Cache .cargo to avoid installing dioxus-cli
      - name: Dioxus cli cache
        id: cache-dioxus-cli
        uses: actions/cache@v3
        env:
          cache-name: cache-dioxus-cli
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo

      # Install dioxus cli if cache misses
      - name: Dioxus cli install
        if: ${{ steps.cache-dioxus-cli.outputs.cache-hit != 'true' }}
        run: cargo install dioxus-cli

      - name: Apt Deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev

      - name: Build
        run: dioxus build --platform desktop
